version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
      args:
        - NODE_ENV=development
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql
      - DB_PASSWORD=1
      - REDIS_HOST=redis
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    command: [
      "sh",
      "-c",
      "npm run seed && npm run dev"
    ]
    depends_on:
      - mysql
      - redis
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
      args: 
        - NODE_ENV=development
    ports:
      - "5173:5173"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - server
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    ports:
      - "5433:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1
      - MYSQL_DATABASE=booking_website
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  mysql_data:
  redis_data:

networks:
  app-network:
    driver: bridge